config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'
  get 'bali', to: 'pages#bali'
  get 'rate_list', to: 'rate_history_entries#index', as: 'rate_index'
  get 'rate_history', to: 'rate_history_entries#history'
  get 'rate/edit', to: 'rate_history_entries#edit'
  put 'rate/update', to: 'rate_history_entries#update'
  delete 'rate/cancel', to: 'rate_history_entries#cancel'
  get 'transactions/refill', to: 'transactions#refill_new'
  post 'transactions/refill', to: 'transactions#refill_create'
  get 'transactions/history', to: 'transactions#history'
  get 'billing', to: 'transactions#billing'

  resources :rates

  resources :users, path: 'members' do
    resources :transactions
    member do
      get :edit_password
      put :update_password
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, except: [:refill_new, :refill_create, :history, :billing]
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @search = @user.transactions.search(params[:q])
    @transactions = @search.result.page(params[:page])
  end

  # GET /transactions/history
  def history
    @search = current_user.transactions.search(params[:q])
    @transactions = @search.result.page(params[:page])
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = @user.transactions.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # GET /billing
  def billing 
    @user = current_user
  end

  # GET /transactions/refill
  def refill_new
    @transaction = current_user.transactions.new
  end

  # POST /transactions/refill
  def refill_create
    @transaction = current_user.transactions.new(transaction_params)
    @transaction.transaction_type = 1
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to root_path, notice: t(:transaction_created) }
      else
        format.html { render :refill_new }
      end
    end
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = @user.transactions.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to user_transactions_path(@user), notice: t(:transaction_created) }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to user_transactions_path(@user), notice: t(:transaction_updated) }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to user_transactions_path(@user), notice: t(:transaction_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = @user.transactions.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:amount, :transaction_type)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.slim
-if @transaction.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @transaction.errors.full_messages.each do |msg|
      li= msg
= form_for [@user, @transaction], :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label t(:transaction_type), :class => 'control-label col-md-2'
    .col-sm-3
      = f.select :transaction_type, options_from_collection_for_select(Transaction::TYPES, :first, :last, @transaction.transaction_type), {:include_blank => true}, {'data-placeholder' => t(:select_type), :class => 'form-control'}
  .form-group
    = f.label t(:amount), :class => 'control-label col-md-2'
    .col-sm-3
      = f.number_field :amount, :class => 'text_field form-control', step: 0.01, min: 0
  .form-group
    .col-md-offset-2.col-sm-3
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), user_transactions_path(@user), :class => 'btn btn-default'

app/views/transactions/billing.html.slim
.page-header
  h1=t(:billing)

.fieldset
  dl
    dt.label.label-default= t(:balance)
    dd
      pre.prettyprint= @user.balance.amount

.form-group
  = link_to t(:back), root_path, :class => 'btn btn-default btn-back'
  '
  = link_to t(:refill), transactions_refill_path, :class => 'btn btn-default btn-money'
  '
  = link_to t(:transactions_history), transactions_history_path, :class => 'btn btn-default'

app/views/transactions/edit.html.slim
div class="page-header"
  h1=t(:edit_transaction)
= render :partial => "form"

app/views/transactions/history.html.slim
.page-header
  h1=t(:transactions_history)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for @search, url: transactions_history_path, class: "form-horizontal" do |f|
      .form-group
        = f.label :created_at_eq, t(:datetime)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :created_at_eq, class: 'search-field form-control'
      .form-group
        = f.label :transaction_type_eq, t(:transaction_type), :class => 'control-label col-md-2'
        .col-sm-3
          = f.select :transaction_type_eq, options_from_collection_for_select(Transaction::TYPES, :first, :last), {:include_blank => true}, {'data-placeholder' => t(:select_type), :class => 'form-control'}
      .form-group
        = f.label :amount_eq, t(:amount)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :amount_eq, class: 'search-field form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr      
      th= sort_link @search, :created_at, t(:datetime)
      th= sort_link @search, :transaction_type, t(:transaction_type)
      th= sort_link @search, :amount, t(:amount)
  tbody
    - @transactions.each do |transaction|
      tr
        td= l(transaction.created_at, :format => :long)
        td= transaction.transaction_type_name
        td= transaction.amount
= paginate @transactions
p
  .page_entries_info
    = page_entries_info @transactions

app/views/transactions/index.html.slim
.page-header
  h1=t(:transactions)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for [@user, @search], class: "form-horizontal" do |f|
      .form-group
        = f.label :created_at_eq, t(:datetime)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :created_at_eq, class: 'search-field form-control'
      .form-group
        = f.label :transaction_type_eq, t(:transaction_type), :class => 'control-label col-md-2'
        .col-sm-3
          = f.select :transaction_type_eq, options_from_collection_for_select(Transaction::TYPES, :first, :last), {:include_blank => true}, {'data-placeholder' => t(:select_type), :class => 'form-control'}
      .form-group
        = f.label :amount_eq, t(:amount)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :amount_eq, class: 'search-field form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr      
      th= sort_link @search, :created_at, t(:datetime)
      th= sort_link @search, :transaction_type, t(:transaction_type)
      th= sort_link @search, :amount, t(:amount)
      th= t(:actions)
  tbody
    - @transactions.each do |transaction|
      tr
        td= l(transaction.created_at, :format => :long)
        td= transaction.transaction_type_name
        td= transaction.amount
        td
          = link_to user_transaction_path(@user, transaction), class: "btn btn-xs"
            = fa_icon "info-circle lg", title: t(:show)

          = link_to edit_user_transaction_path(@user, transaction), class: "btn btn-xs"
            = fa_icon "edit lg", title: t(:edit)

          = link_to user_transaction_path(@user, transaction), class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
            = fa_icon "remove", title: t(:remove)
= paginate @transactions
p
  .page_entries_info
    = page_entries_info @transactions
= link_to t(:new_transaction), new_user_transaction_path(@user), :class => 'btn btn-default btn-new'

app/views/transactions/new.html.slim
.page-header
  h1=t(:new_transaction)
= render :partial => "form"

app/views/transactions/refill_new.html.slim
.page-header
  h1=t(:refill)
-if @transaction.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @transaction.errors.full_messages.each do |msg|
      li= msg
= form_for @transaction, url: transactions_refill_path, :html => { :class => "form-horizontal" } do |f|  
  .form-group
    = f.label t(:amount), :class => 'control-label col-md-2'
    .col-sm-3
      = f.number_field :amount, :class => 'text_field form-control', step: 0.01, min: 0
  .form-group
    .col-md-offset-2.col-sm-3
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), billing_path, :class => 'btn btn-default'
=link_to t(:transactions_history), transactions_history_path

app/views/transactions/show.html.slim
.page-header
  h1=t(:transaction)

.fieldset
  dl
    dt.label.label-default= t(:datetime)
    dd
      pre.prettyprint= l(@transaction.created_at, :format => :long) 
    dt.label.label-default= t(:amount)
    dd
      pre.prettyprint= @transaction.amount

.form-group
  = link_to t(:back), user_transactions_path(@user), :class => 'btn btn-default btn-back'
  '
  = link_to t(:edit), edit_user_transaction_path(@user, @transaction), :class => 'btn btn-default btn-edit'
  '
  = link_to t(:remove), user_transaction_path(@user, @transaction), :method => "delete", :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-danger btn-remove'