config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'
  get 'bali', to: 'pages#bali'
  get 'rate_list', to: 'rate_history_entries#index', as: 'rate_index'
  get 'rate_history', to: 'rate_history_entries#history'
  get 'rate/edit', to: 'rate_history_entries#edit'
  put 'rate/update', to: 'rate_history_entries#update'
  delete 'rate/cancel', to: 'rate_history_entries#cancel'
  get 'transactions/refill', to: 'transactions#refill_new'
  post 'transactions/refill', to: 'transactions#refill_create'
  get 'transactions/history', to: 'transactions#history'
  get 'billing', to: 'transactions#billing'

  resources :rates

  resources :users, path: 'members' do
    resources :transactions
    member do
      get :edit_password
      put :update_password
    end
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  validates :name, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  has_many :rate_history_entries
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  load_and_authorize_resource
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @search = Rate.search(params[:q])
    @rates = @search.result.page(params[:page])
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: t(:rate_created) }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: t(:rate_updated) }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: t(:rate_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:name, :price)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.slim
-if @rate.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @rate.errors.full_messages.each do |msg|
      li= msg
= form_for @rate, :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label t(:name), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_field :name, :class => 'text_field form-control'
  .form-group
    = f.label t(:price), :class => 'control-label col-md-2'
    .col-sm-3
      = f.number_field :price, :class => 'text_field form-control', min: 0, step: 0.01
  .form-group
    .col-md-offset-2.col-sm-3
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), rates_path, :class => 'btn btn-default'

app/views/rates/edit.html.slim
div class="page-header"
  h1=t(:edit_rate)
= render :partial => "form"

app/views/rates/index.html.slim
.page-header
  h1=t(:rates)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for @search, class: "form-horizontal" do |f|
      .form-group
        = f.label :name_cont, t(:name)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :name_cont, class: 'search-field form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr
      th= sort_link @search, :name, t(:name)
      th= sort_link @search, :price, t(:price)
      th= t(:actions)
  tbody
    - @rates.each do |rate|
      tr
        td= rate.name
        td= rate.price
        td
          = link_to rate_path(rate), class: "btn btn-xs"
            = fa_icon "info-circle lg", title: t(:show)

          = link_to edit_rate_path(rate), class: "btn btn-xs"
            = fa_icon "edit lg", title: t(:edit)

          = link_to rate_path(rate), class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
            = fa_icon "remove", title: t(:remove)
= paginate @rates
p
  .page_entries_info
    = page_entries_info @rates
= link_to t(:new_rate), new_rate_path, :class => 'btn btn-default btn-new'

app/views/rates/new.html.slim
.page-header
  h1=t(:new_rate)
= render :partial => "form"

app/views/rates/show.html.slim
.page-header
  h1=t(:rate)

.fieldset
  dl
    dt.label.label-default= t(:name)
    dd
      pre.prettyprint= @rate.name
    dt.label.label-default= t(:price)
    dd
      pre.prettyprint= @rate.price

.form-group
  = link_to t(:back), rates_path, :class => 'btn btn-default btn-back'
  '
  = link_to t(:edit), edit_rate_path(@rate), :class => 'btn btn-default btn-edit'
  '
  = link_to t(:remove), rate_path(@rate), :method => "delete", :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-danger btn-remove'