config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'
  get 'bali', to: 'pages#bali'
  get 'rate_list', to: 'rate_history_entries#index', as: 'rate_index'
  get 'rate_history', to: 'rate_history_entries#history'
  get 'rate/edit', to: 'rate_history_entries#edit'
  put 'rate/update', to: 'rate_history_entries#update'
  delete 'rate/cancel', to: 'rate_history_entries#cancel'
  get 'transactions/refill', to: 'transactions#refill_new'
  post 'transactions/refill', to: 'transactions#refill_create'
  get 'transactions/history', to: 'transactions#history'
  get 'billing', to: 'transactions#billing'

  resources :rates

  resources :users, path: 'members' do
    resources :transactions
    member do
      get :edit_password
      put :update_password
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    = viewport_meta_tag
    title = content_for?(:title) ? yield(:title) : t(:brand)
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :stylesheets
    = yield :javascripts

  body
    nav.navbar.navbar-default.navbar-fixed-top role="navigation"
      .container-fluid
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to t(:brand), root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li.dropdown
              a href="#" class="dropdown-toggle" data-toggle="dropdown"
                =' t(:handbooks)
                span.caret
              ul.dropdown-menu role="menu"
                li
                  = link_to t(:rates), rates_path
            li.dropdown
              a href="#" class="dropdown-toggle" data-toggle="dropdown"
                =' t(:actions)
                span.caret
              ul.dropdown-menu role="menu"
                li
                  = link_to t(:change_rate), rate_index_path
                  = link_to t(:billing), billing_path
            li.dropdown
              a href="#" class="dropdown-toggle" data-toggle="dropdown"
                =' t(:settings)
                span.caret
              ul.dropdown-menu role="menu"
                li
                  = link_to t(:users), users_path
          ul.nav.navbar-nav.pull-right
            li= link_to destroy_user_session_path, method: :delete do
                = fa_icon "sign-out lg", title: t(:sign_out)
    .container-fluid
      .row-fluid
        .col-md-12.well
          = bootstrap_flash
          = yield
      footer
        p
          '&copy; Kawabanda
          = Date.today.year
    = debug(params) if Rails.env.development?

app/views/layouts/logon.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    = viewport_meta_tag
    title = content_for?(:title) ? yield(:title) : t(:brand)
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  body
    .container
      .row
        .col-md-4.col-md-offset-4.well
          = bootstrap_flash
          = yield